# Generated by Django 5.0.6 on 2024-09-23 08:47

import hyd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSATicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General'), ('Personal', 'Personal'), ('others', 'others')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'new'), ('open', 'open'), ('In Progress', 'In Progress'), ('resolved', 'resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, validators=[hyd.models.validate_only_letters])),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseeTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General'), ('Personal', 'Personal'), ('others', 'others')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'new'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[hyd.models.validate_only_letters])),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[hyd.models.validate_only_letters])),
                ('phone_number', models.CharField(max_length=10, validators=[hyd.models.validate_mobile_number])),
                ('Issue_type', models.CharField(choices=[('personal loan', 'Personal Loan'), ('educational loan', 'Educational Loan'), ('car loan', 'Car Loan'), ('business loan', 'Business Loan'), ('Loan Againest Property', 'Loan Againest Property'), ('CreditCard', 'CreditCard'), ('Insurance', 'Insurance'), ('Other Loan', 'Other Loan')], max_length=100)),
                ('description', models.TextField()),
                ('related_application_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
